/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "proto.h"


void
carteiro_rpc_1(char *host)
{
	CLIENT *clnt;
	enum clnt_stat retval_1;
	int result_1;
	char * send_message_1_arg;
	enum clnt_stat retval_2;
	char *result_2;
	char * get_message_1_arg;
	enum clnt_stat retval_3;
	int result_3;
	char * send_image_1_arg;
	enum clnt_stat retval_4;
	char *result_4;
	char * get_image_1_arg;
	enum clnt_stat retval_5;
	int result_5;
	char * send_audio_1_arg;
	enum clnt_stat retval_6;
	char *result_6;
	char * get_audio_1_arg;
	enum clnt_stat retval_7;
	char *result_7;
	char * list_data_1_arg;
	enum clnt_stat retval_8;
	char *result_8;
	char * get_data_1_arg;
	enum clnt_stat retval_9;
	char *result_9;
	char *the_news_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, CARTEIRO_RPC, carteiro_universal_data_transport, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	retval_1 = send_message_1(&send_message_1_arg, &result_1, clnt);
	if (retval_1 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_2 = get_message_1(&get_message_1_arg, &result_2, clnt);
	if (retval_2 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_3 = send_image_1(&send_image_1_arg, &result_3, clnt);
	if (retval_3 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_4 = get_image_1(&get_image_1_arg, &result_4, clnt);
	if (retval_4 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_5 = send_audio_1(&send_audio_1_arg, &result_5, clnt);
	if (retval_5 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_6 = get_audio_1(&get_audio_1_arg, &result_6, clnt);
	if (retval_6 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_7 = list_data_1(&list_data_1_arg, &result_7, clnt);
	if (retval_7 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_8 = get_data_1(&get_data_1_arg, &result_8, clnt);
	if (retval_8 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	retval_9 = the_news_1((void*)&the_news_1_arg, &result_9, clnt);
	if (retval_9 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	carteiro_rpc_1 (host);
exit (0);
}
