/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "proto.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
send_message_1(char **argp, int *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, send_message,
		(xdrproc_t) xdr_wrapstring, (caddr_t) argp,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
get_message_1(char **argp, char **clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, get_message,
		(xdrproc_t) xdr_wrapstring, (caddr_t) argp,
		(xdrproc_t) xdr_wrapstring, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
send_image_1(char **argp, int *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, send_image,
		(xdrproc_t) xdr_wrapstring, (caddr_t) argp,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
get_image_1(char **argp, char **clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, get_image,
		(xdrproc_t) xdr_wrapstring, (caddr_t) argp,
		(xdrproc_t) xdr_wrapstring, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
send_audio_1(char **argp, int *clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, send_audio,
		(xdrproc_t) xdr_wrapstring, (caddr_t) argp,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
get_audio_1(char **argp, char **clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, get_audio,
		(xdrproc_t) xdr_wrapstring, (caddr_t) argp,
		(xdrproc_t) xdr_wrapstring, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
list_data_1(char **argp, char **clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, list_data,
		(xdrproc_t) xdr_wrapstring, (caddr_t) argp,
		(xdrproc_t) xdr_wrapstring, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
get_data_1(char **argp, char **clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, get_data,
		(xdrproc_t) xdr_wrapstring, (caddr_t) argp,
		(xdrproc_t) xdr_wrapstring, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
the_news_1(void *argp, char **clnt_res, CLIENT *clnt)
{
	return (clnt_call(clnt, the_news,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_wrapstring, (caddr_t) clnt_res,
		TIMEOUT));
}
